### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by JoaoOxOc** [isaachinman/next-i18next#1022]
## Describe the bug
This error is happening every time I try to use useTranslation() hook:
TypeError: Object(...) is not a function at Module../pages/_app.jsx

## Occurs in next-i18next version
installed the last version at the time I'm opening the bug

## Steps to reproduce
On a component, add the hook and try to access the page that contains the hook

## Expected behaviour
My _app.jsx contains the export of your library:
export default appWithTranslation(MyApp)

**Comment by isaachinman** [comment]
Hi @JoaoOxOc – you'll need to provide a reproducible repo. Thanks!

**Comment by JoaoOxOc** [comment]
Hi @isaachinman,

I actually found a solution: the problem is in the import `import { useTranslation } from 'next-i18next';` if I use `import { useTranslation } from 'react-i18next';` it works correctly.

I don't have the project yet on a repo, sorry

**Comment by isaachinman** [comment]
You should be able to import `useTranslation` from `next-i18next`. I'd still appreciate a repo to reproduce. Thanks!

**Comment by rntdrts** [comment]
I've just encountered the same error... 
<img width="832" alt="Screenshot 2021-03-24 at 16 33 52" src="https://user-images.githubusercontent.com/3099777/112347503-d16a1f80-8cbe-11eb-9c16-98f64b224e40.png">
The problem is that `useTranslation`, is returning an array. I'm still trying to understand what is the root of the problem.
