### ISSUE TITLE
Page Transitions / Animation and multiple namespaces problem

### ISSUE THREAD

**Issue by emfelipe** [isaachinman/next-i18next#1060]
## Is your feature request related to a problem? Please describe.
I'm using the framer-motion package to create transitions between pages (on route change). This results in a slight delay after clicking the link to give the previous page some time to fade out. Unfortunately, the transition disappears for a moment and shows raw content.

## Describe the solution you'd like
An option to enable having two namespaces at once: one of the previous route and one of the present one.

## Describe alternatives you've considered
Stop using namespaces, move all transitions to one single file.

## Additional context
Maybe it's a problem with the animation framer-motion package? Do you suggest using something else?

**Comment by isaachinman** [comment]
Hi @emfelipe – I have absolutely no idea, and wouldn't be able to help with anything unless you provided a reproducible repo. Moreover, `next-i18next` ultimately just provides props via `getStaticProps` or `getServerSideProps`, so I highly doubt your issue is related to `next-i18next`. Please post on StackOverflow for help. Good luck!
