### ISSUE TITLE
Add e2e test with localeSubpaths enabled

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#118]
Following up on [this comment](https://github.com/isaachinman/next-i18next/pull/96#issuecomment-456379796), it would be good to add an e2e test which has `localeSubpaths` enabled.

This test would be nearly identical to our current e2e test.  The only change would be an added `localeSubpaths: true` in the `userConfig` object passed into `NextI18Next` in `i18n.js`.  Also, any changes to the simple example should be compatible with also using `localeSubpaths`.  I think that we can easily add another e2e test by using the existing example, but having the `localeSubpaths` option be configurable.

Some ideas:
1. Symlink all files in the current example to a new example, with the exception of `i18n.js`, which would be a new file with `localeSubpaths` enabled.  This will most likely cause problems with developers using Windows, as I'm not sure if symlinks work well in Windows.
2. Change the existing example to use an environment variable to set `localeSubpaths`.  `i18n.js` could look something like the following:
```js
const NextI18Next = require('next-i18next')
const localeSubpaths = process.env.USE_LOCALE_SUBPATHS || false

module.exports = new NextI18Next({
  otherLanguages: ['de'],
  localeSubpaths
})
```
In this way, the example can be used for cases where `localeSubpaths` is `true` and `false`, depending on whether or not `USE_LOCALE_SUBPATHS` is defined when we run our tests.

**Comment by isaachinman** [comment]
Not sure about either of those options, to be honest... It'd be really nice if we could just pass the whole config object into the test suite at runtime, so that we can extend this to cover more of the presently "hidden" functionality.

The trouble is that this would require either full rebuilds, or running the app in dev mode with full server reloads.

Regardless of that, there will need to be changes to the puppeteer config. I'm not sure if either of your options take that into consideration? That's the main sticking point here, in my opinion.

**Comment by isaachinman** [comment]
@capellini I finally got around to this. Do you think you will be able to review #186 anytime soon?

A fast follow of #186 will be to remove the custom server example and go back to having a single example. I'd rather that be in docs, rather than a needlessly-hard-to-maintain dir. The approach laid out here will allow us to switch over any/all config options at runtime, and run multiple isolated e2e tests.

**Comment by capellini** [comment]
> Do you think you will be able to review #186 anytime soon?

It's a long weekend here in the US, so I should be able to get to this by Monday at the latest.

> A fast follow of #186 will be to remove the custom server example and go back to having a single example.

What do you think about leaving the `examples/` directory strictly for user examples and moving our e2e tests to the `__tests__` directory?  I imagine that at some point our tests will require a lot of machinations that may needlessly complicate our examples.  Ideally, the example(s) would be clean and easy for users to understand.

**Comment by isaachinman** [comment]
Great, thanks!

> What do you think about leaving the `examples/` directory strictly for user examples and moving our e2e tests to the `__tests__` directory?

I think this is premature. We have a lot of options open to us now that we can flip things inside the config object at runtime. We might need to do that in the future, but for now I'd like to keep things as they are.
