### ISSUE TITLE
useTranslation hook not working properly when imported from 'next-i18next'

### ISSUE THREAD

**Issue by matiasdc1** [isaachinman/next-i18next#1287]
## Describe the bug
I was trying to use this library in my Next.js project. However, after all the setup (I followed all the documentation in the main page), the useTranslation hook was not giving me the information.

`const { t } = useTranslation('home')`
  `console.log(t('title'))`
This codes results in the variable returning 'title'.

I have a home.json with the directory /public/locales/en with:

`{
  "title": "Some data"
}
`

I also have the next snippet in my page component: 

`export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'home'])),
    },
  }`

I finally was able to fix it by switching the import 
`import { useTranslation } from 'next-i18next'`
to 
`import { useTranslation } from 'react-i18next'`

I am not sure If I did something wrong. I hope this post helps anyone with the same problem.

## Occurs in next-i18next version
 "next-i18next": "^8.5.1",

## Expected behaviour
``import { useTranslation } from 'next-i18next'``

Should work as especified in the documentation.

**Comment by isaachinman** [comment]
Can you please provide a reproducible repository?

**Comment by AlejandroGutierrezB** [comment]
Hey I have the same issue with latest version 8.5.3.
You can the config in the following repo:
https://github.com/AlejandroGutierrezB/next-i18next-issue

**Comment by pgrodrigues** [comment]
I ran into the same situation in v8.5.5. A page with:

```
export const getStaticProps = async ({ locale }) => ({
  props: { ...(await serverSideTranslations(locale, ["common", "learn"])) }
});
```

Using:
`const { t } = useTranslation(["common", "learn"]);`

Only the `common` translations will be correctly displayed. For the `learn` namespace it will show the translation keys instead of their values.

Using:
`const { t } = useTranslation(["learn", "common"]);`

I get the reverse result than the one described below.

I didn't try importing directly from `react-i18next` tho.

**Comment by isaachinman** [comment]
@AlejandroGutierrezB I cannot reproduce the issue in that repository. If I change the import to `next-i18next`, everything still works as expected.

@pgrodrigues If you are using multiple namespaces, you should follow [this example](https://www.i18next.com/principles/namespaces#sample). The syntax would be: `t('learn:your_key')`.

**Comment by pgrodrigues** [comment]
> @AlejandroGutierrezB I cannot reproduce the issue in that repository. If I change the import to `next-i18next`, everything still works as expected.
> 
> @pgrodrigues If you are using multiple namespaces, you should follow [this example](https://www.i18next.com/principles/namespaces#sample). The syntax would be: `t('learn:your_key')`.

@isaachinman I missed that part in the i18next docs, it's working now. Cheers.

**Comment by AlejandroGutierrezB** [comment]
Hey @isaachinman thanks for the reply. I was missing  calling `serverSideTranslations` in `getStaticProps` because I thought it would collide with the client side.

Therefore, can I use this library to have dynamic translations in client side?  Or any other package I can use?
Something like:
```json
{
  "title": "Your localized header %{param1}"
}
```

```javascript
const Component = () => {
const [state, setstate] = useState(initialState)
  const { t } = useTranslation('common');
  return (
        <div className="container">
          <h1 className="title">{t('title', { param1: state })}</h1>
```
Thanks in advance and I believe this issue can be closed at least on my side

**Comment by isaachinman** [comment]
Yes, i18next [handles interpolation](https://www.i18next.com/translation-function/interpolation).

**Comment by StephaneBischoff** [comment]
For anyone facing the same issue, also needed to remove `ns` entry from my `next-i18next.config.js` file.
