### ISSUE TITLE
Problem with external locale paths

### ISSUE THREAD

**Issue by mshahov** [isaachinman/next-i18next#14]
Hi,

I am using currently the react-i18next project and have the locale paths configured to an external API. We are using a PHP symfony backend which is generating the language files and are not stored in the next folders. 

With the react-18next I was able by changing configs to make this work, but unfortunately, here I can't make it work. Will there be a way to use external URLs instead of locale paths?

This is more a feature request and that is why I created an issue and not a stackoverflow question. Forgive me if I am wrong.

**Comment by isaachinman** [comment]
Hi @mshahov, thanks for bringing this to my attention. I haven't personally used this methodology, so I'm not very familiar with it.

Just curious - what's the reasoning here? Why not add a build step that fetches all your translation content ahead of time, and serve them from the filesystem? Fetching translations for each SSR run is a very bad idea, as it involves needless network requests, and will increase your TTFB by an enormous amount.

That said, if it's a feature that is supported by `react-i18next`, I'd also like to support it here. Can you provide more details? Ideally I'd like to see a minimal repo to reproduce within.

**Comment by jamuhl** [comment]
@isaachinman it's more or less the same as for custom language detectors -> backend can be from a few types eg. for server the remote or filesystem backends: https://www.i18next.com/overview/plugins-and-utils#backends

**Comment by isaachinman** [comment]
Yeah, it sounds like we just need to expose more options.

Instead of having to add a new option for each individual feature that users run up against, it'd be great to just support any i18next option and spread the object in somehow.

If anyone has an idea how to do that quickly/easily, I'd happily accept a PR.

**Comment by isaachinman** [comment]
To be more clear, the user config is already being [fully spread into the i18next instance options](https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.js#L8). Anyone know why this doesn't "just work" as it already is?

**Comment by isaachinman** [comment]
Is it because you need to call `.use` for these backend plugins?

Can you call `use` after calling `init`? If so, you can just add plugins to the instance generated by `next-i18next`. If not, we'll have to expose an array of plugins to loop through and call `use` with.

**Comment by jamuhl** [comment]
@isaachinman yes `.use` (plugins) have to be added before calling `init` as those get initialized themselves too

**Comment by lucasfeliciano** [comment]
Indeed, but what concerns me is that we have to add two options or interfaces depending if a backend or frontend plugin / detector.

I think the best way to solve this is change at `i18next` level. Would be amazing if as a user we can just call `.use` for a plugin and i18n takes care if needs to be executed in the frontend, backend or both.
The problem here is backward compatibility 

I have some ideas how to solve the problem ( not taking consideration backward compatibility ) but It will be enough to start a discussion about it.

### Detectors

-  Change the interface from `lookup(req, res, options)` to `lookup(options, req, res)` doing that we assure that the implementation will work on both platforms. Then we don't have the need of creating two options `serverDetectors: []` and `browserDetectors: []`

### Plugins

1. The plugin itself should have the condition if it should be executed on server, client or both.
2. i18next could handle that if we add to the plugin the right information.

Example:
[LanguageDetector](https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L25) has the type and i18next perform a [check](https://github.com/i18next/i18next/blob/master/src/i18next.js#L166) on the type to know where it should be added.

If we had am attribute where we specify where the plugin should run `i18next` could check `process.browser` and see if should add or not to that instance.

Doing that we avoid [this](https://github.com/isaachinman/next-i18next/blob/2f24f762dc3cd1103bfc2aa83d5743ac5669794e/src/create-i18next-client.js#L11-L28) kind of repetition, also, avoid passing config options like `serverPlugins, browserPlugins, serverDetectors, browserDetectors`. 

Instead we would have `detectors: [], plugins: []`

**Comment by lucasfeliciano** [comment]
@jamuhl For sure we need to have backward compatibility as priority but since I don't know all the use cases because too fresh into both of the projects code base ( i18next and dependencies and next18next ) your input is super valuable.

About the `process.browser` you are right, it was just for the sake of the example. We could use something like [detect-node](https://github.com/iliakan/detect-node) which is used by `next18next` and thats how I discovered it.

**Comment by mshahov** [comment]
@isaachinman after some discussions with my team, we decided indeed to go with a build step to fetch all translations. Thanks for that! There were still some discussions around this because the idea was that it's a fast developing app with a complete separation between backend and frontend. The backend is used for more than 20 other microsites and mobile apps so it's constantly changing, adding new responses and providing more data so the idea was that we pull all translations and ensure that they will be there, even if we don't change anything on one of the frontend sites.

**Comment by isaachinman** [comment]
Hi @mshahov, I'm glad to hear that you've solved your individual use case via other methods. It sounds like you could further improve your solution with webhooks.

However, the issue of i18next plugin use still remains.

I think we need to separate two matters of concern here:

1. i18next support for `.use` after `.init`.
2. i18next support for client/server detection and "intelligent" use of `.use` depending on environment.

I think the first matter is a great idea, and would make a lot of things easier in the i18next world, including plugin use for `next-i18next`.

I think the second matter is probably a bad idea, and that logic should remain in user land.

@jamuhl Do you think that makes sense? How difficult of a proposal is it to allow `.use` after `.init`? In my mind, we'd just need a block at the end of the `.use` function:

```jsx
if (i18next.isInitialized && !plugin.isInitialized) {
  plugin.init()
}
```

I'm sure it's much more complicated than this, do you mind informing us?

**Comment by jamuhl** [comment]
1) might be doable - just might have side effects like i18next not really ready -> so calling t function before adding those plugins might result in problems...even more for backend implementation that will lead in not loading translations -> as the load is triggered on init and the backendConnecter will just output a warning that no backend was added. Might be we can additional check if it's a backend than we call load for resources again. Got a little fear we do not catch all side effects but hopefully get an initial version working for next.js

2) not sure - but open for suggestions in a PR

**Comment by isaachinman** [comment]
@jamuhl Thanks for explaining. I am now thinking we should not attempt either of those changes... I had a feeling using `.use` after `.init` would lead to some strange issues.

Let's clarify - what's the syntax needed? Is it just a bunch of `.use` calls before one `.init` call? I am leaning back towards simply adding a `use` array to the `next-i18next` config, so in the source we can do:

```jsx
config.use.forEach(x => i18n.use(x))
i18n.init()
```

Does that make sense? Is there something else I am missing?

I would greatly prefer for users to implement their own `.use` plugins, but not at the cost of adding potential bugs/regression to the main i18next codebase.

**Comment by jamuhl** [comment]
@isaachinman @lucasfeliciano  the trickiest part really would be this: https://github.com/i18next/i18next/blob/master/src/i18next.js#L65 --> the backendConnector (loads translations not yet loaded, incl. deduplication of rest calls, retries,...) needs the concrete backend plugin on init already.

So yes, i guess going this road would make things unneeded more complicated.

So doing:

```js
config.use.forEach(x => i18n.use(x))
i18n.init()
```

Seems the best solution to get custom plugins in.

**Comment by isaachinman** [comment]
Okay, I'm going to add this `use` array to the config. Let's leave the i18next source alone.

**Comment by isaachinman** [comment]
Progress will be tracked in #28.
