### ISSUE TITLE
localeStructure without sub-directory keeps searching for subdirectory

### ISSUE THREAD

**Issue by bartrail** [isaachinman/next-i18next#1500]
## localeStructure without sub-directory keeps searching for subdirectory
When changing the configuration to use a flat directory structure like this, so I can use files like `common.en.json` or `something-else.fr.json` there is an error thrown, expecting the language directory to be there.

configuration:
```
const path = require('path')

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de', 'fr'],
  },
  localeStructure: '{{ns}}.{{lng}}',
  localePath: path.resolve('./public/translations'),
}
```

Error:
```
Error: ENOENT: no such file or directory, scandir '/Users/con/work/project/app/public/translations/de'
at Object.readdirSync (fs.js:1047:3)
at getLocaleNamespaces (/Users/con/work/project/app/node_modules/next-i18next/dist/commonjs/config/createConfig.js:180:23)
at /Users/con/work/project/app/node_modules/next-i18next/dist/commonjs/config/createConfig.js:188:20
at Array.map (<anonymous>)
  at getNamespaces (/Users/con/work/project/app/node_modules/next-i18next/dist/commonjs/config/createConfig.js:185:44)
  at createConfig (/Users/con/work/project/app/node_modules/next-i18next/dist/commonjs/config/createConfig.js:228:29)
  at _callee$ (/Users/con/work/project/app/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:199:53)
  at tryCatch (/Users/con/work/project/app/node_modules/regenerator-runtime/runtime.js:63:40)
  at Generator.invoke [as _invoke] (/Users/con/work/project/app/node_modules/regenerator-runtime/runtime.js:294:22)
  at Generator.next (/Users/con/work/project/app/node_modules/regenerator-runtime/runtime.js:119:21) {
    errno: -2,
    syscall: 'scandir',
    path: '/Users/con/work/project/app/public/translations/de'
  }
```

## Occurs in next-i18next version
8.8.0

## Steps to reproduce
change the configuration to the one above

## Expected behaviour
The loading of the files works as expected.

## Additional context
I did some debugging in the `createConfig.js` from node-modules and found out, that the `combinedConfig` variable is filled correctly and these variables also look correct:

```        
var defaultLocaleStructure = localeStructure.replace("".concat(prefix, "lng").concat(suffix), lng).replace("".concat(prefix, "ns").concat(suffix), defaultNS);
var defaultFile = "/".concat(defaultLocaleStructure, ".").concat(localeExtension);
var defaultNSPath = path.join(localePath, defaultFile);
var defaultNSExists = fs.existsSync(defaultNSPath);

console.log(defaultLocaleStructure);
console.log(defaultFile);
console.log(defaultNSPath);
console.log(defaultNSExists);
```

outputs:

```
common.de
/common.de.json
/Users/con/work/project/app/public/translations/common.de.json
true
```

So I think the problem relies in some un-configured namespace configuration below where path is concatinated without respecting the combined config.

```
var namespacesByLocale = locales.map(function (locale) {
return getLocaleNamespaces(path.resolve(process.cwd(), "".concat(serverLocalePath, "/").concat(locale)));
});
```

**Comment by isaachinman** [comment]
Sounds like you've debugged it thoroughly. Would definitely accept a PR for this bug fix if you have the time?

**Comment by bartrail** [comment]
I will try to do this in the next couple of days ✌️

**Comment by BeckerNico** [comment]
I've created a [PR](https://github.com/isaachinman/next-i18next/pull/1546) for this Issue.
The basic idea is that there is a check wether the language is part of the folder structure or of the filename. If it is part of the folder structure we continue as always. 
But if the language is part of the filename we assume that files of multiple languages were placed in one folder. Then we get all files of that folder and remove the language from the filename to get unified namespaces. The language is removed with a regex that will only match if the language is not part of a word. This prevents that a filename like `default.de.json` will be `fault` and not `default`. I have also written some tests for that regex and for the new structure. 
If i unterstood Issue https://github.com/isaachinman/next-i18next/issues/1116 correct, this schould also be fixed with this PR. 
Let me know if anything is missing :)

**Comment by isaachinman** [comment]
@BeckerNico Much appreciated! However, I don't think this should be solved via a regex. The solution should be declarative via the templating syntax.

**Comment by isaachinman** [comment]
Perhaps check the i18next ecosystem for inspiration, as this is where the [templated path option](https://github.com/i18next/i18next-fs-backend#backend-options) comes from.

**Comment by BeckerNico** [comment]
@isaachinman i adjusted the PR by removing the regex and using only the templating syntax to extract the namespace from the filename. What do you think?

**Comment by bartrail** [comment]
thx @BeckerNico for taking care of this :v:

**Comment by bartrail** [comment]
@isaachinman did you have time to look into the updated PR?

**Comment by isaachinman** [comment]
@bartrail @BeckerNico Here are my thoughts:

Based on comments like https://github.com/isaachinman/next-i18next/issues/1202#issuecomment-947779838:

> I would recommend against allowing a custom localePath as this makes it not able to be statically analyzable and it will not be able to detect the files being needed automatically.

I think the most "custom" fs support we'd proceed with in `next-i18next` would be to allow the _user_ to provide a custom function to resolve files/namespaces, instead of trying to predict and support all possible permutations.

I am envisioning a future state where `next-i18next` has a rigid expectation of `./public/locales/{{locale}}/{{namespace}}.{{ext}}`, and if you want to use _anything else_, you will need to provide your own resolution function.

I am very hesitant to merge a PR like #1546, as it will just lead to further and further edge cases pop up, as the possibilities are literally infinite.

**Comment by lucaslcode** [comment]
Hi @isaachinman, I am thinking to make this PR as you said, since [Couchers](https://github.com/Couchers-org/couchers/) is transitioning to NextJS and we need this functionality.

I was thinking to keep `localeStructure/Extension` for backwards compatibility, and overload `loadPath` to take a function as with other `i18next` backends, in which case `localStructure/Extension` would be ignored. How does that sound?

**Comment by isaachinman** [comment]
@lucaslcode I think we'd be better off introducing a new/dedicated config property, rather than overriding any i18next props.

**Comment by lucaslcode** [comment]
@isaachinman my bad sorry - I meant override `localePath`, not `loadPath`

**Comment by lucaslcode** [comment]
@isaachinman this is coming along. I just have a question about the workings that I can't quite figure out. 

You're using `i18-fs-backend` as the backend by default. This only works on node afaik, yet you're creating a separate config for the client which strips `/public` from the path to the translation files. Does the client actually use the files or is there some other reason for this? Does that mean the resources by necessity need to be in the public directory in order to be reachable from the client?

Thanks so much!

**Comment by isaachinman** [comment]
> Does that mean the resources by necessity need to be in the public directory in order to be reachable from the client?

If you want it to work out of the box, yes. The docs are [here](https://nextjs.org/docs/basic-features/static-file-serving).

Let me know if I can answer any other questions, and a massive thanks for digging into this!
