### ISSUE TITLE
Customize Default_CONFIG_PATH

### ISSUE THREAD

**Issue by felixtsangDev** [isaachinman/next-i18next#1656]
I want to customize my default config path, as I currently developing a nextJs project in nx repo, and I found that there is no easy way to overwrite the DEFAULT_CONFIG_PATH instead of changing the library in node_modules

Is it possible to overwrite it like the way of overwriting localePath?

**Comment by isaachinman** [comment]
There's no hard requirement for this as you can already [pass any config object you want in manually](https://github.com/isaachinman/next-i18next#unserialisable-configs), and bypass a config path entirely.

Moreover, `DEFAULT_CONFIG_PATH` _needs_ to be a constant string, and cannot be a runtime variable, because it needs to be statically analysable for webpack to work.
