### ISSUE TITLE
Option to change the language without using the URL

### ISSUE THREAD

**Issue by munafio** [isaachinman/next-i18next#1746]
Hi there,
How we can change user language without using the url and headers detection! .. 

The issue with the URL is that the user when get back to the website, the language will be returned to the default language `(e.g. en)` not the language that the he have selected last time he visited the website `(e.g fr)`.

So I want to store the language at `localStorage` on my app's settings page .. then Next.js app get the language from the `localStorage`.

How we can achieve that?

Thanks

**Comment by isaachinman** [comment]
Please check the NextJs documentation. This functionality is not handled by `next-i18next`.

**Comment by munafio** [comment]
@isaachinman do you have an idea about how to achieve this? example? I have searched a lot about this issue but I got nothing to help!!

**Comment by isaachinman** [comment]
Read the main documentation:

https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection
https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie

If you have any questions please use StackOverflow.

**Comment by ChristopherHButler** [comment]
@munafio did you find a suitable solution to do this? If so, would you mind sharing?

**Comment by ChristopherHButler** [comment]
@isaachinman I'm not sure this statement is correct:

> This functionality is not handled by next-i18next.

next.js has support for internationalised routing.

So next.js does by default detect the locale (language-region-script) and automatically re-route the user based on locale. You can also change the locale yourself by simply adding a button and an onClick handler something like the following:

```js
  const onToggleLanguageClick = (newLocale) => {
    const { pathname, asPath, query } = router;
    router.push({ pathname, query }, router.asPath, { locale: newLocale });
  };
```

But this re-route's the user. You cannot just change / select a language, it is tied to locale and routing.
As a user of `next-i18next` I want to be able to select the set of translations to use independent of the user's locale.

Tying language to locale makes an assumption about the user that they speak the language in the region they are browsing from. If I use myself as an example, I am an English speaker, but live in Norway. So I want to select language, regardless of my region.

With `react-i18next` I can do this with the `changeLanguage` function. It seems there is no equivalent offered from `next-i18next`. If `next-i18next` is responsible for deciding which set of translations to use then I believe you should be able to provide a `changeLanguage` function to do this.

Does this make sense / seem reasonable @isaachinman or have I misunderstood something?

**Comment by adrai** [comment]
https://github.com/i18next/next-i18next/blob/master/examples/simple/pages/index.js#L61

**Comment by ChristopherHButler** [comment]
Thanks @adrai but this still changes the locale. The language is dependant upon the locale (i.e. region). Is it possible for these to be independent?

**Comment by adrai** [comment]
Like already mentioned before... the language detection is handled by next.js
https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection
https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie

fyi: your example English in Norway in theory you would need this accept-language header: `en-NO`... but I don't know if this will ever work, because it is not a "standard".
So it would be simpler if your accept-language header was `en` only...
How is your accept-language header currently set? (basically what is: `navigator.languages` in your browser?)

**Comment by ChristopherHButler** [comment]
Thank you, I have read the next documentation and understand that next does by default, detects the locale (language-region-script) and automatically re-route the user based on locale (as mentioned in my comment above). 

You may also note that you can disable this behaviour if you choose: [https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection](https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection)

Not to repeat myself but I want to be able to select the set of translations to use independent of the user's locale.

What you seem to be saying is that `next-i18next` decides which set of translations to use based on the locale information from next.js. What I am suggesting is that the user of `next-i18next` (i.e. me as a developer) should be able to manually change the set of translations used.

Your response indicates that the set of translations used is dependant on the locale information detected by next.js and I am arguing that, while that is a good default, it should be possible to choose independently.

**Comment by adrai** [comment]
fyi: in theory you could do something like this:

```js
export const getServerSideProps = async ({ locale, req }) => {
  // inspect header accept-language header and set locale to your desired value
  if (req.headers['accept-language'].indexOf('en-NB') > -1) locale = 'en'
  return {
    props: {
      ...await serverSideTranslations(locale, ['common', 'footer']),
    },
  }
}
```

this would set the locale language to the actual language you want to show without changing the route...

**Comment by aabmets** [comment]
@adrai What @ChristopherHButler was saying was that he wants the ability to change the language that the webpage is displayed in without any change in the URL that is displayed to the client browser. Like in regular React: click button -> content changes language, URL remains the same.

**Comment by aabmets** [comment]
The solution is to use a different i18next package: [medium article](https://iamsannyrai.medium.com/i18n-in-next-js-without-sub-path-or-domain-routing-2443c1a349c6)

**Comment by shettayyy** [comment]
@ChristopherHButler would https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie solve your issue?

**Comment by yantakus** [comment]
@shettayyy `NEXT_LOCALE` only works with internationalized routing. It just helps to redirect the user to, let's say, `example.com/en/page` when you go to `example.com/page`.

**Comment by aabmets** [comment]
So actually I found a solution which can be implemented using this library, but it requires server-side rendering. Also, you must use the pages/ folder with getServerSideProps(). What you do is disable Next.js automatic locale detection and redirection completely and manually store a locale cookie on client side. When client makes the request to the Next.js backend, the server reads the cookie and renders the page in the language that is specified in the cookie and then returns that rendered page to the client. You might think that "Damn, that must be resource heavy always rendering those pages", but no! Actually, what you do in production is that you put a reverse-proxy like NGINX, Apache or Traefik between the client and your Next.js server (Express on Node), which caches the requests based on the request cookie contents. This way, the reverse proxy will serve the client a pre-cached page of the website and your backend is spared from having to re-render the same page over and over again. You can set up re-caching rules so that when the data changes on the source page, the reverse proxy will make a new copy of the page. Eventually, the reverse-proxy cache will contain copies of all the locale versions of your website and serve them to the clients. This works also for user account pages, which content depends on the user account. You can just create the page with placeholders, so that the page is rendered with loader spinners and then the data itself is fetched on client-side. Easy peasy. 😄

**Comment by aabmets** [comment]
> fyi: in theory you could do something like this:
> 
> ```js
> export const getServerSideProps = async ({ locale, req }) => {
>   // inspect header accept-language header and set locale to your desired value
>   if (req.headers['accept-language'].indexOf('en-NB') > -1) locale = 'en'
>   return {
>     props: {
>       ...await serverSideTranslations(locale, ['common', 'footer']),
>     },
>   }
> }
> ```
> 
> this would set the locale language to the actual language you want to show without changing the route...

So yeah, that's the gist of the solution, but you also must disable the automatic language detection and redirection by Next.js. Also, there is a problem with correctly setting the `<html lang=''>` property, because Next.js changes it automatically only when its language autodetection is used, meaning that you will need to set it yourself manually. Also, it's a brainfuck to do it manually, because Next.js does not provide a simple and elegant solution to change the lang property yourself. You kinda need to hack the _document.tsx file and altogether, its shit.

**Comment by micktg** [comment]
> The solution is to use a different i18next package: [medium article](https://iamsannyrai.medium.com/i18n-in-next-js-without-sub-path-or-domain-routing-2443c1a349c6)

It works, thank you.
But it's hard to believe that one needs to get another package to make such a basic functionality work!

**Comment by nikita-fxbytes** [comment]
> The solution is to use a different i18next package: [medium article](https://iamsannyrai.medium.com/i18n-in-next-js-without-sub-path-or-domain-routing-2443c1a349c6)


Hello
I am  using next js 14 how can I implement this package in it

**Comment by aabmets** [comment]
@nikita-fxbytes 
I use [next-international](https://github.com/QuiiBz/next-international) for my projects, works very well.

This is the content of the `middleware.ts` file to rewrite requests from a locale subpath to root path:
```javascript
import { createI18nMiddleware } from 'next-international/middleware'
import { NextRequest } from 'next/server'

const I18nMiddleware = createI18nMiddleware({
  locales: ['et', 'en'],
  defaultLocale: 'et',
	urlMappingStrategy: 'rewrite'
})

export function middleware(request: NextRequest) {
  return I18nMiddleware(request)
}

export const config = {
  matcher: ['/((?!api|static|.*\\..*|_next|favicon.ico|robots.txt).*)']
}
```

**Comment by bejoyfuuul** [comment]
Thank you, @aabmets, [next-international](https://github.com/QuiiBz/next-international) works well.

I put a lot of thought into choosing the i18n library, and thanks to that, I found a way to make it work without changing the route.

[document](https://next-international.vercel.app/docs) pages also good.

**Comment by hechang000** [comment]
It works for me. To make `changeLanguage` work, you need to add this to _app.js That will initialize the i18n

```
import { appWithTranslation } from 'next-i18next';
import nextI18NextConfig from '../next-i18next.config'; // Import the next-i18next config
...

function App({ Component, router, pageProps }) {
  const { query } = router;

  return (
...
}
```

export default appWithTranslation(App, nextI18NextConfig);
