### ISSUE TITLE
[Question] Is it possible to translate with i18n.t("phrase") instead of props.t("phrase") with HOC?

### ISSUE THREAD

**Issue by sigo** [isaachinman/next-i18next#219]
I've tried translate phrases with `i18n.t("phrase")` but this only works for client site, and server just returns the keys.

**Comment by isaachinman** [comment]
What exactly are you trying to do? When you're accessing the `t` function, is `tReady` true?

**Comment by sigo** [comment]
Hmm. It's little hard to me to exactly explain the problem. I'll just prepare example repository with pointed problem.

**Comment by isaachinman** [comment]
Okay, I'll take a look when that's ready.

**Comment by isaachinman** [comment]
@sigo Any update?

**Comment by sigo** [comment]
@isaachinman sorry for waiting. Repo is available at: https://github.com/sigo/example-next-i18next

It's pure `nextjs` app with `typescript` and `next-i18next`. You need run only: `yarn/npm i` and `yarn dev/npm run dev`.

I think code should explain my problem and this is what I'm trying to do. My way comes from `i18next` documentation (https://www.i18next.com/overview/getting-started):

```
import i18next from 'i18next';

i18next.init({
  lng: 'en',
  debug: true,
  resources: {
    en: {
      translation: {
        "key": "hello world"
      }
    }
  }
}, function(err, t) {
  // initialized and ready to go!
  document.getElementById('output').innerHTML = i18next.t('key'); // 👈 LOOK HERE
});
```

and will be great, if it is possible with `next-i18next`.

**Comment by isaachinman** [comment]
So, this _does_ work on the client side. The reason this does not work during SSR is because the main `i18n` instance is _cloned_ for each request, and is located at `req.i18n`. You can see that [here](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L53).

In short, if you want to do stuff with the `i18n` instance on the server, you need to make sure you're using `req.i18n`. It's going to be pretty hard to do that deeply nested within your React tree. Is there a reason why you're trying to do it this way? The whole reason `withNamespaces` (and the context provider) exists is to solve this problem.

Let me know if this answers your question.

**Comment by sigo** [comment]
Thanks, I understand now.

Only reason for trying another way is that I don't like using HOC in most component. If translations will be possible without wrapping, it will be great for me.

However, if it isn't possible, thanks for answer and your time.
