### ISSUE TITLE
opt-out trailing slash in index page url

### ISSUE THREAD

**Issue by Ktchan825** [isaachinman/next-i18next#283]
## Is your feature request related to a problem? Please describe.
Enabling the localeSubpaths, `www.example.com/zh` is redirected to `www.example.com/zh/` while `www.example.com/zh/any` wont be redirect to `www.example.com/zh/any/`
I would like to have a consistence pattern in the url format

## Describe the solution you'd like
Add a new config options.

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by isaachinman** [comment]
The trailing slash is helpful, because it helps us ensure the difference between routes like:

```
myapp.com/en
myapp.com/enable
myapp.com/en/able
```

This will be further complicated by requests like #279. However, it is of course possible to remove the `force-trailing-slash` util and replace it with more sophisticated logic.

@capellini Any interest in picking this up? Otherwise it'll go into the backlog and I'll work on it as time allows.

**Comment by capellini** [comment]
@isaachinman I'll see what I can come up with.

**Comment by isaachinman** [comment]
@capellini As you want - I have a good idea how to achieve this and can take care of it. Only thing is that I'm incredibly busy and it might be several weeks.

**Comment by capellini** [comment]
@isaachinman Actually, if you already have something in mind, it'd probably be best that you implement it when you get the chance.  I'm more than willing to review, when ready.
