### ISSUE TITLE
Any example on using remote backend

### ISSUE THREAD

**Issue by s4kh** [isaachinman/next-i18next#288]
## Is your feature request related to a problem? Please describe.
It seems it must use node-fs-backend no matter what. If my resources are on remote server how to fetch

## Describe the solution you'd like
Example on how to use remote backend plugin. Provided backend plugin will override node-fs-backend

## Describe alternatives you've considered
```
module.exports = new NextI18Next({
  ...config,
  defaultLanguage: 'en',
  otherLanguages: OTHER_LANGUAGES.concat(DEFAULT_LANGUAGE),
  use: [nmdsBackend]
})
```

**Comment by isaachinman** [comment]
You can use whatever `i18next` settings you'd like. In this case we're talking about `i18next-express-middleware` settings. The config is completely overridable. You might want to take a look at #163. Otherwise, just play around with the config options [seen here](https://github.com/i18next/i18next-express-middleware).

Let me know if you have any specific issues. I've never actually had this use case myself, so am unable to provide you with an example.

**Comment by s4kh** [comment]
If we look at i18next documents you can use different types of backend plugins, right? `i18next-node-fs-backend` only works with files. But there is a locize service that we need to fetch our resources from remote server not from file. In that case how would we use this package?

**Comment by isaachinman** [comment]
Yes, you can add plugins via [`config.use`](https://github.com/isaachinman/next-i18next#options). It's true that this package is primarily aimed at filesystem approaches, and I've explained my bias against serving localisation content over network requests in several places.

That said, if you have any concrete suggestions on how to improve functionality for different backend types, I am happy to discuss!

**Comment by adrai** [comment]
https://github.com/locize/next-i18next-locize
