### ISSUE TITLE
Using translation values as keys for default language breaks SSR

### ISSUE THREAD

**Issue by jmikrut** [isaachinman/next-i18next#289]
## Describe the bug
If you use translation _values as keys_ for a default language, i.e. `t('Here is a key')`, you can remove the need to maintain static locale JSON for your default language. This is supported client-side, although with `next-i18next`, SSR breaks for any pages that have missing namespace JSON.  

## Occurs in next-i18next version
0.23.7

## Steps to reproduce
1. Set up a repo with default config, use values as key for default language.

```js
t('Here is a test')
```

2. Write out JSON for namespaces as you normally would for other languages besides your default language. Don't write out JSON for your default language. Instead, let the key itself act as the default locale string. 

`/static/locales/br/common.json`:

```json
{
    "Here is a test" : "Aqui está um teste"
}
```

3. This will all work as expected on client. But, when trying to SSR in production, all pages with missing locales will not server-render. Pages with locale data, for example in this case any pages relying solely on the namespace `common` and rendered in the `br` locale, will SSR properly.  Client rendering still works as expected on all locales.

## Expected behaviour
I expect server-rendered versions of pages that use keys as values if no JSON is present.

## Screenshots
N/A

## OS (please complete the following information)
 - Device: MBP 2017 15", deployed via Heroku
 - Browser: All / NA

## Additional context
It seems to me that this should be supported, although it's possible that we are using the `i18next` package incorrectly. If so, I apologize in advance!

**Comment by ebsalberto** [comment]
I can confirm this happens in react-i18next 10.9.0 and next-i18next 0.37.0

**Comment by isaachinman** [comment]
@jmikrut @ebsalberto Sounds like a bug that should be opened in the `react-i18next` repo. We're not handling anything specific to the translate function here.

**Comment by jmikrut** [comment]
I will move this there, but first - a clarifying question, so I understand—

The `t` function works perfectly and is doing its job. SSR is broken but the page displays properly once run on the client.  

The only thing that doesn't work in the configuration above is SSR within NextJS. It seems to me that `react-i18next` doesn't have anything to do with NextJS or its SSR, and that's what this repo aims to solve.  Correct? 

If I go to `react-i18next` blabbering about SSR I have a feeling they are going to tell me to come back here...

**Comment by isaachinman** [comment]
@jmikrut If you provide a reproducible repository I can take a look for you.

**Comment by ebsalberto** [comment]
@isaachinman just added you

**Comment by isaachinman** [comment]
Hi guys - if you'd like my help please provide a _minimal reproducible example_ which is fully public. Thanks.

**Comment by jmikrut** [comment]
Sure thing.  Here you go:

https://github.com/keen-studio/next-i18next-ssr-demo

Just need to clone and install. Further testing shows that you can get _**only the first page loaded**_ to server-render properly, and then all pages after do not SSR.  So, load up the `index.js` page, and then try to load the `about.js` page.  View source for both.

**Comment by isaachinman** [comment]
@jmikrut There is no `en` directory of namespaces in that repo. Running `yarn build && yarn start` therefore fails.

**Comment by jmikrut** [comment]
Ah - right.  I just added a `.gitkeep` into that folder to keep the dir around. Pull and try again?

**Comment by isaachinman** [comment]
@jmikrut There are no files in the `en` dir.

**Comment by jmikrut** [comment]
Exactly - that's the point of this issue.  If you use the full string value as the key, `react-i18next` displays the key itself for the default language.  This avoids the need for default language JSON and creates a bit of a better development experience while reading through JSX.

**Comment by isaachinman** [comment]
Putting aside the issue of whether this is actually a good idea or not... You will immediately see your issue fixed if you just add empty JSON files at `en/home.json` and `en/about.json`.

Your fallback system will now work, as the namespaces can be loaded, and `i18next` detects the _lack of a key in that namespace_. What's not expected, however, is for entire namespaces to be missing.

If you really feel as though you want your use case supported, this should probably be raised as a bug in either `i18next-node-fs-backend`, `i18next-express-middleware`, or `react-i18next` - not entirely sure. Jan would be able to point you in the right direction. If it turns out we need to do something on the `next-i18next` side of things too, I'm happy to do so.

In general this is not an industry standard (or indeed even recommended) approach.

Please realise that your fallback system will work just fine if you omit the idea of your fallbacks being another language in their own right. You either need to provide localised content to have "a language", or you can fall back to keys. You won't get your desired combination out of the box for free.

**Comment by ebsalberto** [comment]
Thank you for looking into this. Can you expand briefly on why this is not a good idea?

**Comment by isaachinman** [comment]
As I just explained, it conflates the ideas of languages and fallbacks. If you want to fallback to a key, the expectation is not that all your keys are in a separate language themselves.

More generally, it will lead to a hard to maintain system. What happens when you want to slightly change a localisation value for SEO reasons, content reasons, or simply grammar corrections? Do you also update the key? Normally one would expect localisation _keys_ to remain constant from the moment they are created, whereas localisation _values_ are free to change constantly.
