### ISSUE TITLE
Fetch translations files from S3

### ISSUE THREAD

**Issue by cs-dcyntler** [isaachinman/next-i18next#336]
## Describe the bug
Okay, so currently we serve translations file on `/static/locales`. It's working fine, but we have to change source to public S3. We try to implement `backend` section in config. Code looks like:
```javascript
const i18n = new NextI18Next({
  defaultLanguage: defaultLanguage,
  otherLanguages: languages.filter(lang => lang !== defaultLanguage),
  backend: {
    loadPath: 'http://localhost:3000/static/locales/{{lng}}/{{ns}}.json', // it is example url
    ajax: async (url, options, callback) => {
      try {
        const { data, status } = await axios(url);
        callback(data, { status });
      } catch (err) {
        console.error(err);
      }
    },
  },
});
```
With this code requests coming out (I see on Chrome DevTools->Network) but that does not change anything after request successful and is translation key rendered instead value of this key. In my opinion it is because translations should be fetching before render (on server side). It looks like server side doesn't call above code. How I can resolve this problem? What is the best method to fetch translations json files from external server?

Here is our server.js:
```javascript
const { existsSync } = require('fs');
const express = require('express');
const next = require('next');
const nextI18NextMiddleware = require('next-i18next/middleware');
const routes = require('./src/routes');
const { config } = require('dotenv');

if (!existsSync(`${__dirname}/.env`)) {
  console.log('File .env does not exist!');
  process.exit(1);
}

config();
const nextI18next = require('./src/i18n').i18n;

const app = next({ dev: process.env.NODE_ENV !== 'production' });
const handle = routes.getRequestHandler(app);

(async () => {
  try {
    await app.prepare();
    const server = express();
    server.use(nextI18NextMiddleware(nextI18next));
    server.get('*', (req, res) => handle(req, res));
    await server.listen(3000);
    console.log('> Ready on http://localhost:3000');
  } catch (err) {
    console.error(err);
  }
})();
```

## Occurs in next-i18next version
0.40.0

## OS (please complete the following information)
 - Device: Linux
 - Browser: Chrome

**Comment by isaachinman** [comment]
> What is the best method to fetch translations json files from external server?

As a build step, writing to the filesystem, in my opinion. Otherwise, this exact topic has been discussed several times in other issues on this repo, eg #163.

**Comment by cs-dcyntler** [comment]
@isaachinman, thank you so much for fast reply.

**Comment by BjoernRave** [comment]
@isaachinman I'm sorry, that I have to bother you again with this. If it was for me I would just add them as a build step like you suggest, but the requirements from above are that I need to get them from S3 as well. When looking at https://github.com/isaachinman/next-i18next/issues/163 the solution provided is this one, right: https://github.com/isaachinman/next-i18next/issues/163#issuecomment-461072570 ? So I added 
```  
server.get('/static/locales/', (req, res) => {
    console.log('test');
  });
```
just to check if it actually hits that route, but when I start the server it crashes, because it cannot find the local files like you mentioned in https://github.com/isaachinman/next-i18next/issues/163#issuecomment-461205013

**Comment by isaachinman** [comment]
@BjoernRave No problem. Let's work through it together.

What happens if you set your `config.backend` to something else? Take a good look through the `react-i18next` docs, as that's what these configuration options are. We may need to put `i18nextNodeBackend` into the default value for `config.use`, thereby allowing users to eject out of it.

**Comment by BjoernRave** [comment]
@isaachinman yea, let's do it. 

I added 
```
  backend: {
    loadPath: createLoadPath,
    ajax: axios
  }
```
where createLoadPath is a function to generate the path to the file on s3 as defined in the `i18next-xhr-backend`, but I get the same error. I already tried to comment out `i18next-node-fs-backend'` in `create-i18next-client.js` and the function in `create-config.js` which checks if it's node or not. 
Then I get a problem with the `allLanguages` array. I will investigate further to make it work.

From my understanding if we get the translations from a remote source, we don't need to distinguish between server and client.  

So maybe we could check if config.backend is set

**Comment by BjoernRave** [comment]
@isaachinman if you are up for it, we could maybe start a skype/disccord/sth. call and try to solve this.

**Comment by isaachinman** [comment]
Happy to discuss here, but this project is entirely OSS and has no budget for support.

What is your problem with `allLanguages`?

In general, any approach of fetching translations from a remote source is going to be an entirely `i18next` and `react-i18next` concern, and won't be related directly to `next-i18next`.

**Comment by BjoernRave** [comment]
@isaachinman and as soon as you start a call it's budget? But okay.

for some reason `allLanguages` is undefined and `fallbackLng` is equal to `['dev']` and setting those in my config doesnt get recognized

**Comment by isaachinman** [comment]
No one will be providing you with personal calls to support your use of this OSS. We can continue discussion here so that the outcome might at least be useful to others.

It sounds like you are having a general problem with setting config options. Can you post a minimum reproducible example of this?

> So you're saying I could achieve this without next-i18next?

Yes.

> Is the file loading the only thing that next-i18next brings to the table? ... I also like that you can set the localeSubPaths

No - you answered your own question.

**Comment by BjoernRave** [comment]
@isaachinman my intent was to work together on something to contribute to this repository

I sent you an invite to a private repo on github containing the minimum reproducible example

**Comment by isaachinman** [comment]
Can you please make the reproducible example public, and post the link here? Let's keep a public record of all communication for future users.

**Comment by BjoernRave** [comment]
okay, here is the link: https://github.com/BjoernRave/next-i18next-remoteFetch/tree/master

**Comment by isaachinman** [comment]
That repo is broken:

```
Module not found: Can't resolve 'next-i18next'
```

Regardless, why does your `loadPath` function return the same URL for all languages and namespaces?

It makes sense that your config is broken, you commented out the entire server side config logic.

**Comment by BjoernRave** [comment]
@isaachinman I just added it for the example. I actually have a function in place which resolves to the s3 file, but I did not want to include it.

I guess you need to run `yarn && yarn build inside the next-i18next folder first`

I will check how I can make it work without commenting out everything, but the thing is that inside there you are checking for the local files, so I need to rewrite it/ add another conditional to change the way we load the logic on the server

**Comment by BjoernRave** [comment]
@isaachinman I checked again the server side config logic, but without success. From my understanding what you are doing in there is to add `loadPath` and `addPath` , which should not be necessary in my case, because I add them in my own config. Then there is `ns`, where you get all available namespaces in local, but I can also set that in my own config, right? And then there is `preload`, which by the way could just be set to true inside the server side config logic, or? At least the i18next docs say its necessary for SSR.

So I modified the config code to this: 

```
  if (isNode && !process.browser) {
    // const fs = eval("require('fs')")
    // const path = require('path')

    // const getAllNamespaces = p => fs.readdirSync(p).map(file => file.replace('.json', ''))
    const {
      allLanguages, defaultLanguage, localePath, localeStructure,
    } = combinedConfig

    combinedConfig = {
      ...combinedConfig,
      preload: true,
      // ns: getAllNamespaces(path.join(process.cwd(), `${localePath}/${defaultLanguage}`)),
      backend: {
        // loadPath: path.join(process.cwd(), `${localePath}/${localeStructure}.json`),
        // addPath: path.join(process.cwd(), `${localePath}/${localeStructure}.missing.json`),
      },
    }
  }
```
but it's the same.

**Comment by StarpTech** [comment]
Hi @BjoernRave I faced with the same issue and solve it. There are only few things to   note.

1. Configure `loadPath` in your i18n client for the browser.
```js
const NextI18Next = require('next-i18next/dist/commonjs');
const { localeSubpathOptions } = require('next-i18next/dist/commonjs/config/default-config');
const i18nConfig = require('./i18n-config');

// next-i18next defaults
const localePath = 'static/locales';
const localeStructure = '{{lng}}/{{ns}}';
const localeExtension = 'json';

module.exports = new NextI18Next({
  ...i18nConfig,
  backend: {
    queryStringParams: { buildId: process.env.BUILD_ID },
    loadPath: `${process.env.assetPrefix || ''}/${localePath}/${localeStructure}.${localeExtension}`,
    addPath: `/${localePath}/${localeStructure}.missing.${localeExtension}`
  }
});
```
2. (optional) With `queryStringParams` you can ensure that you always fetch the latest translations based on the `buildId` which needs to be exposed via `env` in `next.config.js`.
3. `assetPrefix` points to your S3 bucket or CDN.
4. On server-side you don't need to change your configuration because it use the filesystem middleware. That's why you shouldn't change the default settings `localePath` should still point to your local folder.

**Comment by BjoernRave** [comment]
@StarpTech and it works for you? You can load translations from a remote source, without having them in the locales folder? Because all you are doing differently is the way you get the loadPath. Also why are you importing `LocalSubPathOptions` ? If it works for you, do you think you can provide a working repo?

**Comment by StarpTech** [comment]
@BjoernRave yes it works! 

> Also why are you importing LocalSubPathOptions ? If it works for you, do you think you can provide a working repo?

Sry this was needed to use different `localeSubpaths` but shouldn't be relevant for this issue.

**Comment by StarpTech** [comment]
@bjoernrave

> without having them in the locales folder?

No, I have them in both CDN (client) + filesystem (server)

**Comment by isaachinman** [comment]
Is there anything further to discuss in this issue?

**Comment by jashan-preet-singh-dhanoa** [comment]
I have faced CORS blocked error when try to load common.json file from an external link like the amazon s3 server. is there any solution for this. I have already true, false the crossDomain parameter under the backed object.

Access to XMLHttpRequest at 'https://xxx.s3.amazonaws.com/v2/locales/de/common.json' from origin 'http://xyz.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by GainorB** [comment]
@jashan-preet-singh-dhanoa Have you figured this out?

**Comment by atellezsazo** [comment]
Hi @BjoernRave, how did you solve the issue to have both CDN (client) + filesystem (server)? I just notice that using the backend configuration the server returns just the translations keys without using CDN or filesystem locale files for SSR.

**Comment by BjoernRave** [comment]
@atellezsazo  Hey, in the end I switched to use https://github.com/vinissimus/next-translate , because `next-i18next` doesnt support serverless architecture. I didnt solve the problem

**Comment by atellezsazo** [comment]
@BjoernRave thanks for your reply!

**Comment by isaachinman** [comment]
Just want to note that `next-i18next@beta` does indeed support serverless (but not vercel at the moment).
