### ISSUE TITLE
Compatibility with Next.js 9 (getting rid of Express?)

### ISSUE THREAD

**Issue by martpie** [isaachinman/next-i18next#380]
## Is your feature request related to a problem? Please describe.

Next.js 9 was released this morning, with a lot of improvements that may simplify the usage of this pluging.

https://nextjs.org/blog/next-9#api-routes

## Describe the solution you'd like

Ideally, being able to use next-i18next without having to setup a custom Express instance/file.

## Describe alternatives you've considered

I have no idea how this could be done (and I do not think it is even doable), but maybe the new API routes provide a catch-all/middleware section (but I did not see any so far) that could help us achieving this.

## Additional context

This is more a discussion about feasibility that a feature request 🚀

**Comment by isaachinman** [comment]
That was quick!

Couple things to say:

1. We are already tracking removal of the Express dep via #274 
2. Otherwise, `next-i18next` should be fully compatible with NextJs v9

Unless there are compatibility concerns outside of the Express work, I think we can close this issue. Bugs can be raised if/when they are found.

**Comment by martpie** [comment]
Awesome, thanks!
