### ISSUE TITLE
DefaultLanguage is not applied.

### ISSUE THREAD

**Issue by arsendev** [isaachinman/next-i18next#396]
I am currently working in Korea. The simple example is used, but the defaultLanguage is set to 'en' but it is still applied to 'ko'. What should I modify? This is my code below. [I'm sorry I turned the translator around and asked questions.]

i18n.js
```
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig
const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
  browserLanguageDetection: true,
  defaultLanguage: 'en',
  otherLanguages: ['en','ko', 'zh', 'jp'],
  localeSubpaths,
  serverLanguageDetection : true
})
```

next.confit.js
![code](https://user-images.githubusercontent.com/51102399/61343044-5fa1c780-a887-11e9-8d1f-70cb304d9205.png)

result console
![consolelog](https://user-images.githubusercontent.com/51102399/61343106-92e45680-a887-11e9-8099-165aca817b18.png)
![console](https://user-images.githubusercontent.com/51102399/61343111-97107400-a887-11e9-9484-e578f427a22a.png)

I want defaultLanguage to be applied as 'en'.

**Comment by isaachinman** [comment]
Sorry, I don't understand your question. Please bear in mind that in some cases, the language chosen will depend on your _browser settings_, and if you want to override that, you'll need to play around with `config.detection`.

On a side note, it seems you've misunderstood the `publicRuntimeConfig` part. Sorry, I see how that could be confusing. We're passing `process.env.LOCALE_SUBPATHS` into our simple example so that we can run headless tests in multiple config modes on the same app. For your own app, just choose one string value. You don't need any environment vars.

For further help, please post on StackOverflow.
