### ISSUE TITLE
Support Automatic Prerendering

### ISSUE THREAD

**Issue by phakphumi** [isaachinman/next-i18next#429]
## Is your feature request related to a problem? Please describe.
Next9 provides a new feature Automatic Prerendered. Anyway, next-i18next required to define `namespacesRequired: []` to `getInitialProps` in the page-level component which will always turn off Automatic Prerendering feature by Next9.

## Describe the solution you'd like
I want to take advantage of Automatic Prerendering while using next-i18next.

## Additional context
There is some case that the page doesn't fetch any data just show the static page with text. So, taking advantage of Automatic Prerendering will be useful for the performance.

**Comment by isaachinman** [comment]
Defining `namespacesRequired` is not required, just recommended to "codesplit" your namespaces instead of sending them all down with every request.

In general, `next-i18next` will require a custom server and full SSR until serverless middleware support lands (see #274).

Even more generally speaking, you can't prerender static HTML for a page which by definition needs to serve multiple languages.
