### ISSUE TITLE
middleware is removing the query

### ISSUE THREAD

**Issue by KhodorAmmar** [isaachinman/next-i18next#53]
the code in the middleware that adds the lng param is essentially removing all other queries

`app.render(req, res, url.replace("/".concat(lng), ''), {
        lng: lng
      });
`

For example:

`/page?foo=bar` will pass the req query object { foo: 'bar' }, but if you go to `/ar/page?foo=bar` the query object will become { lng: 'ar' }.

Instead the middleware should **add** the lng

`app.render(req, res, url.replace("/".concat(lng), ''), {
        lng: lng,
        ...req.query
      });
`

**Comment by isaachinman** [comment]
Do you mean [this line](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.js#L18)? It's not quite the same as what you copy/pasted above... Not sure where that came from.

> the query object will become { lng: 'ar' }

Do you not think it's useful to have the lang as a key in the query object? We specifically _need_ to pass the lang query with `as` to Next so that it understands the route.

If all you want to do is spread the remaining queries into the `app.render` call, that's totally fine. Do you want to submit a PR, or shall I handle it?

**Comment by KhodorAmmar** [comment]
Yes that’s the line. I copied from the built version instead. I can handle the PR, I’ll send it today, thanks!
