### ISSUE TITLE
Remove core-js dependency

### ISSUE THREAD

**Issue by schneck** [isaachinman/next-i18next#580]
The core-js dependency collides with a more recent core-js 3 version, if present.
In addition, it looks like the dependency was not needed any more. I can't find any usage in the whole project except in the package file

**Comment by isaachinman** [comment]
As a package, we have no control what dependencies a user may or may not install.

The dep is being used [here](https://github.com/isaachinman/next-i18next/blob/88033719baf46dd7bc0ca02f0cc35b0e98bce8af/.babelrc#L26).

**Comment by bitworking** [comment]
I think a library should not include any polyfills. Because you don't know which devices are targeted.

**Comment by isaachinman** [comment]
We target the same that NextJs does out of the box, because this is a NextJs plugin.

**Comment by bitworking** [comment]
NextJs has "@babel/runtime-corejs2" as dependency which is not a problem.

**Comment by isaachinman** [comment]
@bitworking If you can put forth a PR that removes polyfills but retains IE11 support, it will be merged immediately.

**Comment by bitworking** [comment]
I want to put a PR but the Pre-commit-hook doesn't let me commit since the latest update. I get following errors:

node_modules/i18next-express-middleware/index.d.ts(9,7): error TS2687: All declarations of 'i18n' must have identical modifiers.
node_modules/i18next-express-middleware/index.d.ts(9,7): error TS2717: Subsequent property declarations must have the same type.  Property 'i18n' must be of type 'i18n & { options: Config; }', but here has type 'i18n'.
types.d.ts(65,7): error TS2687: All declarations of 'i18n' must have identical modifiers.

Can it be that you don't run those checks by yourself?

**Comment by isaachinman** [comment]
@bitworking If I clone this repository, pull latest `master`, and do `yarn && yarn lint && yarn test`, everything passes.

No, I do not commit or push with `--no-verify`. Moreover, we have CI that runs on each commit/PR.

Please provide more details.

**Comment by bitworking** [comment]
@isaachinman ok thanks. I'll try again. Perhaps I have another TypeScript version locally..
