### ISSUE TITLE
Navigator detection - sometimes displaying translation keys

### ISSUE THREAD

**Issue by Accumulative** [isaachinman/next-i18next#628]
Hello, sorry in advance if I have misunderstood something.

## Describe the bug
Translation keys are sometimes displaying instead of the translations in the case of using navigator for browser language detection.

## Steps to reproduce
1. Clone this repo and cd into it
2. yarn install && yarn build
3. cd examples/simple
4. Replace the i18n.js with the following: 
```
const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
  otherLanguages: ['de'],
  detection: {
    order: ['navigator'],
  },
})
```
5. yarn install && yarn run dev
6. Navigate to / - works for en, but footer doesn't work for de
7. Click through to /second-page - works for en and de
8. Refresh on second-page - works for en, but not de
9. Navigate by URL to second-page - works for en, but not de

## Expected behaviour
I expected the translations to display regardless of the actions the user performs

## Additional info
I tried adding debug true to the i18n config, and I saw some logs about missing keys. Between logs about switching to en, and then to de.

**Comment by isaachinman** [comment]
Hi @Accumulative. These config options come from upstream i18next packages. In this case, take a look at [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector).

The behaviour you're describing sounds like there's a mismatch between server and client detection, which would make sense if you're only using `navigator`.

Look at the default values that `next-i18next` provides:

```jsx
order: ['cookie', 'header', 'querystring'],
```

Cookies are a good top-priority detection, because they're available on both the server and the client. The default settings above allow the server to detect language on new traffic from either headers or querystring, and then set a cookie. The client subsequently only reads the value from the cookie. This ensures good synchronisation.

Ultimately your config is up to you! If you do believe you've found a bug, it's likely within the i18next source. Good luck!

**Comment by Accumulative** [comment]
Your explanation makes a lot of sense. 
I didn't know about these defaults, they work very well. Thank you very much.
