### ISSUE TITLE
Custom localePath is not work when navigate or change language

### ISSUE THREAD

**Issue by vimutti77** [isaachinman/next-i18next#63]
I use next and express to create server. I use next-i18next to create multilingual web app.
I have project structure
```
├── dist/      # Built files
├── public/    # Static files (locales)
└── src / 
    ├── component/      # Components
    ├── lib/            # Store i18n.js
    ├── pages/          # Pages
    └── server.js
```
And file i18n.js
```
const NextI18Next = require('next-i18next')

module.exports = new NextI18Next({
  localeSubpaths: true,
  otherLanguages: ['fr'],
  localePath: 'public/locales/'
})
```
Everything work fine on page start. But when I navigate to other page with `Link` provided by this lib or change language with `i18n.changeLanguage(i18n.language === 'en' ? 'fr' : 'en')}`. The new language is not loaded properly.

I found that the server is still try to download the locale files from `/static/locales`

**Comment by vimutti77** [comment]
I have found the solution. just use express.static to map static path to target path like
```
server.use('/static/', express.static(path.join(__dirname, '../public')))
```
And problem is now gone.

**Comment by isaachinman** [comment]
That's correct. That's just a next/express problem, and has nothing to do with `next-i18next`.

**Comment by kachkaev** [comment]
I had the same error when setting things up for the first time. By defining `localePath: 'blah'` I expected that things would just keep working both on the client and the server. But as it turned out, the client was still fetching translations from `/static/locales`, which returned 404. My solution was to create a symlink inside `/static/` to `blah` and things began working again. Perhaps, if `localePath` was defined [in server.js](https://github.com/isaachinman/next-i18next/blob/46158794e138bb8f9d725110777092a7f9dc6ebf/example/server.js#L14) and `express.static` was auto-configured, things would be a bit easier for a newcomer.

**Comment by isaachinman** [comment]
PRs are always welcome.

**Comment by kachkaev** [comment]
I've reflected on this problem in https://github.com/isaachinman/next-i18next/issues/42, which I'd like to discuss first before submitting the PRs with fixes 😉  Will get back to you when I've got some time.
