### ISSUE TITLE
Default `i18next.language` value not set on first render

### ISSUE THREAD

**Issue by gwendall** [isaachinman/next-i18next#639]
Hello, as the title describes, I have this problem. However, the value gets set once I change it manually with `i18n.changeLanguage`.

Here is a small reproduction : https://github.com/gwendall/next-i18next-bug
And try visiting http://localhost:3000/en

**Comment by isaachinman** [comment]
Working fine for me. I presume this is because you've modified `config.detection`, and your browser language header is something other than English.

`config.detection` is set up in a very intentional way - please do read through past issues and documentation to understand.

If you feel this is a genuine bug, please let me know. I think it's just a result of user configuration. Good luck!
