### ISSUE TITLE
Update core-js to 3

### ISSUE THREAD

**Issue by shunkakinoki** [isaachinman/next-i18next#713]
for the next major version, an update for core-js to 3 will be nice!

Previously discussed here (#707)

**Comment by chrisinajar** [comment]
With all dependencies up to date, this is now the only package in my stack that uses core-js 2. I've had to switch over to configuring babel to transpile the module, and i import from `dist/es` in order to get the source files to then be transpiled using core-js 3. I did that with `next-transpile-modules` for the main app and `node -r babel-register.js server.js` in order to get the development server to start. `@babel/register` is only needed on the server side because of this module, otherwise it could be written in pure commonjs and work with the raw node binary with no extra options.

If I import from `dist/commonjs` (or the root import) at all then the app wont start.

I hope this helps someone, I spent like 3 hours trying to get this to work.

**Comment by WsCandy** [comment]
Just incase anyone else comes accross this, currently the older version of `core-js` included in this package breaks the `nomodule` polyfills included with next > 9.3. You can replicate this by cloning down a new project, including next-18next, setting up a simple implmentation and adding a simple hook to the homepage that calls `Promise.finally` or any other methods that should be polyfilled.

You can follow the steps outlined by chrisinajar above to correct this problem. Unfortunately I'm using Typescript so I had to jump through some extra hoops.

Instead of using `babel-register` I simply created two config files one for the server and one for the client, which is not ideal but it's fixed my issues for now, so I'm happy to sit on it until there's a release that addresses the problem.

It would be good if this could be updated as it's currently breaking the bundled polyfills with next.

**Comment by isaachinman** [comment]
I'm happy to release a `core-js` update on `v5` if someone wants to put together a PR, and ensure that we only have one version of `core-js` being loaded in. The reason we pinned the dep is to save bundle size.
