### ISSUE TITLE
Multiple translation files not working in 5.0.0-beta

### ISSUE THREAD

**Issue by fabrii** [isaachinman/next-i18next#762]
## Describe the bug
Multiple translation files not working.

## Occurs in next-i18next version
5.0.0-beta.4

## Steps to reproduce

SecondPage.getInitialProps = async () => ({
  namespacesRequired: ['common', 'footer', 'anotherFile'],
})

export default withTranslation(['common', 'anotherFile'])(SecondPage)

## Expected behaviour
The content of both files has to be taken into account

**Comment by borispoehland** [comment]
First of all, the description of your issue is pretty bad, but I think I know what you're trying to achieve.

In the `withTranslation` HOC, only the first namespace can be used without prefix. All the other ones (in your case `anotherFile`) have to be prefixed with the filename:

t('**anotherFile:**translationFromOtherFile')

**Comment by fabrii** [comment]
> First of all, the description of your issue is pretty bad, but I think I know what you're trying to achieve.
> 
> In the `withTranslation` HOC, only the first namespace can be used without prefix. All the other ones (in your case `anotherFile`) have to be prefixed with the filename:
> 
> `t('anotherFile:translationFromAnotherFile')`

You are right. Sorry for the mistake.

Thank you.
