### ISSUE TITLE
Unsupported language showing as initial language if detected by browser

### ISSUE THREAD

**Issue by Nelrohd** [isaachinman/next-i18next#78]
## Expected Behavior
My browser has currently has vietnamese, english then french languages however my application is setup for english and french language. From that, I expect to see my website in English.

## Actual Behavior
My website is in english but shows vietnamese as current language.
<img width="336" alt="screen shot 2019-01-04 at 4 27 28 pm" src="https://user-images.githubusercontent.com/1664480/50681544-7779d280-103e-11e9-9394-ca86b2831d3e.png">

## Steps to Reproduce the Problem

  1. Setup in your browser vietnamese as top language
  2. Set this configuration:
```
{ defaultLanguage: 'en', otherLanguages: ['fr'], fallbackLng: 'en' }
```

## Specifications
  - Version: next-i18next@0.16.0
  - Platform: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
  - Subsystem: OSX 10.13.6

**Comment by isaachinman** [comment]
Sorry - what exactly is the bug here? You don't want to see `vi` in `i18n.language`? If anything, you'll probably want to open this issue in [react-i18next](https://github.com/i18next/react-i18next/) as it seems like an issue on that side of things.

You'll notice that the `languages` array contains `en` too. This means that i18next is _trying_ to serve the client Vietnamese, but is falling back to English because Vietnamese isn't available.

**Comment by Nelrohd** [comment]
@isaachinman it should not show `vi` as `language` but `fr` or `en`. Is it still a `react-i18next` issue?

**Comment by isaachinman** [comment]
Yes, `next-i18next` is not setting `language` or `languages`, that's all i18next territory.
