### ISSUE TITLE
Custom server support

### ISSUE THREAD

**Issue by mercteil** [isaachinman/next-i18next#782]
Why would you remove the custom server support?

I use custom route patterns and some other middlewares in my project (eg. also next-i18next).

From v5.0 it makes it extremely hard for me to update this package since I would probably rewrite and refactor a lot of code.

Isn't it possible to return the middleware functionality for custom servers ?

**Comment by isaachinman** [comment]
Custom servers are actively discouraged by the NextJs team, and for pretty good reasons. It was a "hack" in some sense, that this package used for quite some time to support specific cookie/middleware/redirect functionality.

I won't be actively maintaining support for custom servers, because now that we have `rewrites` and have removed our Express dependency, they simply aren't necessary. All version previous to `v5.0.0` support custom servers, and can be used as long as you'd like – no need to refactor immediately.

For an idea of what an upgrade path would look like, you can check: https://github.com/isaachinman/next-i18next/pull/689#issuecomment-666113984. I'm hoping to gather more information like this and update the docs.
