### ISSUE TITLE
Parent component should automatically import namespacesRequired from child.

### ISSUE THREAD

**Issue by sebastienlabine** [isaachinman/next-i18next#866]
Let's say I have a parent component **HomePage** that uses **Footer** inside it's render function.

Inside my footer component, I have declared
```js
class Footer extends React.Component<WithTranslation> {
public static async getInitialProps() {
    return {
      namespacesRequired: ['footer']
    }
  }
}
export default withTranslation(['footer'])(Footer)
```
However, when rendering then home page, I see the key before the actual translation. To fix this, I need to ask the Home page to load the footer translation file.

```js
class Homeextends React.Component<WithTranslation> {
public static async getInitialProps() {
    return {
      namespacesRequired: ['home', 'footer']
    }
  }
}
export default withTranslation(['home', 'footer'])(Home)
```

Would it be possible to automatically import the child translation file as a namespacesRequired?

**Comment by isaachinman** [comment]
At the moment, no. Page components are different than "normal" components in NextJs, in that they are wrapped by `_app`, and we can compose on top of them.

To be absolutely clear, there is _no such thing_ as `getInitialProps` (or other data-fetching methods) on non-page components in NextJs (ie your footer example here).

We have previously experimented with tree-traversal in `next-i18next`, and abandoned it due to performance implications.

The current solution is a bit of a compromise, but one that has been working reasonably well. Let me know if you have any further questions.

**Comment by sebastienlabine** [comment]
Understood. In that case, do you think docs could reflect this use case / the flashing issue, I think people can look a long time for an answer before finding it.

**Comment by isaachinman** [comment]
Do you feel like [this section](https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies) of the docs is not clear enough?
