### ISSUE TITLE
ICU macros

### ISSUE THREAD

**Issue by hazem3500** [isaachinman/next-i18next#880]
## Is your feature request related to a problem? Please describe.
In our project, we are using the ICU format and we wanted to use the [ICU macros](https://react.i18next.com/misc/using-with-icu-format#using-babel-macros-trans-plural-select) but am not sure how do I use them with next-i18next.

**Comment by kachkaev** [comment]
You can find an example here: https://gitlab.com/kachkaev/website-frontend/-/blob/master/src/i18n.ts. Note that next-i18next has not been upgraded for some time in that project. I plan to do this once #869 is resolved.

Also note that the issues in the repo should [follow a template](https://github.com/isaachinman/next-i18next/tree/master/.github/ISSUE_TEMPLATE).

**Comment by isaachinman** [comment]
@kachkaev Can anything be done within `next-i18next` to make this easier for users?

**Comment by kachkaev** [comment]
Hi @isaachinman! I don't think I have an answer at this point. I can look into this once there is a version for Next.js 10. Overall, adding ICU to next-i18next should not differ to much to just using `i18next-icu`: https://github.com/i18next/i18next-icu

The only tricky optimisation I can think of is dynamically importing `'i18next-icu/locale-data/LANG'` so that the client bundle had to download just one lang based on the current route.

**Comment by isaachinman** [comment]
> The only tricky optimisation I can think of is dynamically importing 'i18next-icu/locale-data/LANG' so that the client bundle had to include just one file based on the current route.

Can be done via a dynamic import, I imagine.

Should we leave this issue open?

**Comment by kachkaev** [comment]
> Can be done via a dynamic import, I imagine

Yeah true. For that though, there's a need for `async initiI18next(currentPageLocale)` function of some sort, in which configuration process happens. This is where the lib can load all the necessary plugins and asynchronously import the ICU data for a specific lang. And maybe fetch namespace data too?

> Should we leave this issue open?

Up to you really 🙂 I personally don't think that ICU integration is the job of `next-i18next` since ICU is just a yet another i18next plugin.

**Comment by isaachinman** [comment]
@hazem3500 Do you feel like your issue is solved, with the links and help that @kachkaev has shared, or do you want to keep this open?

**Comment by hazem3500** [comment]
@kachkaev I can't really open the link you've sent, probably an issue with GitLab, could you paste the code here?

I've managed to add ICU support like so
```ts
// i18n.ts
import NextI18Next, { InitConfig } from 'next-i18next'
import path from 'path'
import ICU from 'i18next-icu'

const icu = new ICU()

const I18nInstance = new NextI18Next({
    localePath: path.resolve('./public/static/locales'),
    use: [icu],
} as InitConfig)

export const {
    appWithTranslation,
    Link,
    Router,
    Trans,
    config,
    i18n,
    initPromise,
    useTranslation,
    withTranslation,
} = I18nInstance

export default I18nInstance
```

Is there anything that I am missing?
