### ISSUE TITLE
nextI18NextMiddleware for Koa?

### ISSUE THREAD

**Issue by foreseaz** [isaachinman/next-i18next#9]
Checking out the src of [middlewares](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.js), now only support express, may I know is there plan to support Koa? Thanks.

**Comment by isaachinman** [comment]
I'm not a koa user, so I'm not too sure how that'd work.

@jamuhl is [koa-i18next-middleware](https://www.npmjs.com/package/koa-i18next-middleware) a 1:1 replacement for `i18next-express-middleware`?

**Comment by isaachinman** [comment]
Okay. This will definitely need to come from someone who personally uses koa and can ensure things are set up correctly and functional. I have absolutely no idea if we could achieve parity, but my initial assumption is that this would be very difficult or impossible if there isn't a pre-existing 1:1 solution.

**Comment by isaachinman** [comment]
Ah, also just to mention - this impacts our own [next-i18next-middleware](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.js) in addition to the need for a 1:1 replacement for `i18next-express-middleware`.

Again I'm not a koa user, but it seems like the same `.use` function exists, so that might work without any modification.

**Comment by jamuhl** [comment]
Really someone using koa should look into this. Also, i would give the next-i18next some time to stabilize before adding support for koa.

**Comment by isaachinman** [comment]
@jamuhl Absolutely agreed. My initial impression is that support for koa will never be added, but someone might come along and surprise me.

**Comment by jamuhl** [comment]
fully agree...and yes...i would be surprised too...

**Comment by foreseaz** [comment]
lol, why surprised? Because Koa is seldom used in community?

**Comment by jamuhl** [comment]
@foreseaz not because of koa - because it's not so easy - you will need to understand: next.js, koa, i18next, react-i18next and next-i18next

**Comment by isaachinman** [comment]
`next-i18next` depends upon several other open source packages. The main problem here is that `i18next-express-middleware` handles a _lot_ of otherwise complicated logic for us involving the delivery of translation content.

We would need a 1:1 koa replacement of `i18next-express-middleware` in order for `next-i18next` to support koa, and that simply doesn't exist.

I'm going to close this issue for now - if anyone in the future feels as though it's worth discussing again, just let me know.

**Comment by Abramovick** [comment]
I'm also using koa, any updates on having a koa version?

**Comment by Janealter** [comment]
@Abramovick try this https://github.com/winstrike/next-i18next-koa

**Comment by isaachinman** [comment]
@Janealter Does that fork work? First time I have seen it.

**Comment by Abramovick** [comment]
@Janealter thanks man. Is the difference only the use of [`koa-i18next-middleware-fixed`](https://github.com/janealter/koa-i18next-middleware-fixed) instead of [`i18next-express-middleware`](https://github.com/i18next/i18next-express-middleware)?

**Comment by Abramovick** [comment]
Also am i missing something? The notes say "@isaachinman cannot support koa until a 1:1 replacement for i18next-express-middleware exists"... I thought [`koa-i18next-middleware-fixed`](https://github.com/janealter/koa-i18next-middleware-fixed) is acting as the replaced...?

**Comment by isaachinman** [comment]
@Abramovick I hadn't heard of `koa-i18next-middleware-fixed` until now, and am not entirely sure it will be a good choice in the long run.

We might be able to provide a bailout option where users can just pass their own middleware function, though.

**Comment by Janealter** [comment]
@isaachinman Yes, it does. But not 1:1.

**Comment by Janealter** [comment]
@Abramovick, besides using `koa-i18next-middleware-fixed`, I rewrote some parts of the code, you can see it in the repository [`next-i18next-koa`](https://github.com/winstrike/next-i18next-koa)

**Comment by Janealter** [comment]
@isaachinman `koa-i18next-middleware-fixed` is the fixed version of [koa-i18next-middleware`](https://github.com/lxzxl/koa-i18next-middleware). I published this package until @lxzxl approved my pull requests with necessary fixes.

> We might be able to provide a bailout option where users can just pass their own middleware function, though.
This is a good idea but it is not enough just to replace middleware, we still need to rewrite some other parts of the code that depend on the type of server. In a good way, we need to redo the library structure so that it gives the choice of server to use, koa or express.

**Comment by isaachinman** [comment]
> we need to redo the library

If this project was to be refactored at all, it would be done to be completely agnostic of server framework, and would operate in an entirely serverless manner (vanilla `req` and `res`). See #274.

**Comment by sep2** [comment]
I am using koa2 server also, any updates on this?
