### ISSUE TITLE
Questions about i18next-http-backend and client-side only translations

### ISSUE THREAD

**Issue by LeonardDrs** [isaachinman/next-i18next#967]
Hey, I feel like I'm missing something huge:

I don't get how and when `i18next-http-backend` is doing something.
Since we always need a `serverSideTranslations` usage to retrieve translations, and the `i18next` instance is only being created when using `serverSideTranslations`, I have no idea when we could fetch translations on the client-side.

This relates to another question I'm asking myself:
Is there a way to create a `i18next` instance without using `serverSideTranslations`?
Like if a page only needs to be created on the client-side, how the `i18next` instance is supposed to be created?

**Comment by isaachinman** [comment]
Hey @LeonardDrs. Thanks for all your help recently, and I really appreciate that you have clearly taken a deep dive into the code. Let me answer your two questions:

> I don't get how and when i18next-http-backend is doing something

I was actually just thinking this myself recently – since we're now treating translation data as props, and passing that off to NextJs, I think we _can_ remove `i18next-http-backend`. In previous versions, we [relied on it heavily inside `getInitialProps`](clientLoadNamespaces), which is called on the client side upon route navigation.

There are some "nice to have" features that `i18next-http-backend` provides, like detected and adding missing translations, but we should probably just kick that out to userland, as people can always pass anything into `use`.

> if a page only needs to be created on the client-side, how the i18next instance is supposed to be created?

Not sure I get your meaning. An i18next instance will be created by [this line](https://github.com/isaachinman/next-i18next/blob/next-v10/src/appWithTranslation.tsx#L34), both in server contexts and in client contexts. Have I misunderstood your question?

**Comment by LeonardDrs** [comment]
I'm glad I can be helpful!

I agree to your first point, but it could be related to the second question:

>Not sure I get your meaning. An i18next instance will be created by this line, both in server contexts and in client contexts. Have I misunderstood your question?

Yeah but we only reach this line if `props?.pageProps?._nextI18Next` is [true](https://github.com/isaachinman/next-i18next/blob/next-v10/src/appWithTranslation.tsx#L23). 
Which mean that if we don't use `serverSideTranslations` - like when the user wants to **not** use `getServerSideProps` / `getStaticProps` - we never create the i18next instance.
In which case the user would instanciate i18next himself and `i18next-http-backend` would provide useful. But all could be done in the userland.
So my question would be:
How should the user instanciate i18next himself in such case?

**Comment by isaachinman** [comment]
Why would a user _not_ want to use one of NextJs' data fetching methods? That is the main way that `next-i18next` is proposing to handle translations.

Can you give an example use case?

**Comment by LeonardDrs** [comment]
I agree with you and I have no such example. I may have been over-thinking.

Which leads me to another over-thinking thought: 

What if the user want to lazy load translations on a particular page - like a modal containing unique translations or something.
Do we agree to not lazy load the translations and have them always fetched in the `serverSideTranslations` of the page, even if the user may never load the modal?

I think it's perfectly fine, just wanted to clarify.

**Comment by isaachinman** [comment]
You are now getting into more nuanced problems with localisation, @LeonardDrs. The short answer is that it's a somewhat unsolved problem, and in general the solution will be to treat our translations more like code, than content, and treeshake/bundle them with tools like webpack.

For now, the `next-i18next@beta` functionality is about as good as it gets, in terms of industry standards.

**Comment by LeonardDrs** [comment]
Yeah I agree, thanks a lot for your time and thoughts!

Shall we close this issue or do you want to use it to keep track of `i18next-http-backend` modifications?

**Comment by isaachinman** [comment]
@LeonardDrs I've addressed this in #971. Also reduces the bundle size of `next-i18next` by ~10%. Thanks!

**Comment by LeonardDrs** [comment]
My pleasure, thank you for your awesome work!

**Comment by LeonardDrs** [comment]
Oups, was a bit too hasty. Will let the merge close this one
